name: Npm Publish

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17
          registry-url: https://registry.npmjs.org/
      - run: pnpm
      - run: pnpm build ngx-cz-id --prod
      - run: pnpm publish dist/libs/ngx-cz-id --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17
          registry-url: https://npm.pkg.github.com/
      - run: pnpm
      - run: pnpm build ngx-cz-id --prod
      - run: pnpm publish dist/libs/ngx-cz-id
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
